# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-26 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2000, null=True)),
                ('link', models.CharField(max_length=2000)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(max_length=2000, null=True, upload_to=b'')),
                ('published_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_time'],
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2000, null=True)),
                ('xml_url', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=2000, null=True)),
                ('published_time', models.DateTimeField(blank=True, null=True)),
                ('last_polled_time', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(max_length=2000, null=True, upload_to=b'')),
            ],
            options={
                'verbose_name': 'Feed',
                'verbose_name_plural': 'Feeds',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rssfeed.Feed'),
        ),
    ]
